language: node_js
node_js: 4
script:
  - npm install
  - npm run build
deploy:
  provider: releases
  api_key:
    secure: XWuj8GfoHzfdmyitdRjAo9Jt2EFL96ZME3fafwW68b/9T+tGRn1F0ms25xDnQ3E6Ukmm4lfE0UGbY6eFmx/Z3JuueboPf0w5g6yepWP9UvShaW1M+RUv0q406Rl2BpVs1Cl8pwNfBgq+vdiyFsJtx4R/aT4Hr4NLGZIBHy9icGOGfBHsnQ2c+Bv8weacIrjAtIRewc5K3xNy3L7jucupTJOMY7C8P1nIfODtBC57w5Xob3Q3ddvDpw9nfdhwHs4wGtr8/9RfI7uDOJ7ymCTZcW15OP8xy1vnWchKo8tqzs3ahMFIduTXxdrIhIc3NzLDybUF4ENGtWWrnNu8U1TdeCSB3fZNf5sot+JIyXY9aqtOr5p3zM0UdjD03rIf5/ZtpFbctJCGTpiEd+BCfbk6752rEOxOx4quXIvelXvgUdD8bnlzvzvQv67K8ruyF23NiIB6ty0vPW4JdD+QyImrK/OC9QJ19phdP69325DWFNmW3VsNZzlSiq9284Z26jh67Z/Ac0n2v4aLCekVv2GU+8Ka2qm8dRkr6KbugVPjyHM6W51XG6sJy7PlgTra8vkkQlQu9JzZxjE9C6mP4s+7j1ej9Fr8h/CddtRP6GO1xhWznNRxauYeU3qBXGb2EdnNwl16/Cze33W35L69RxJaJd2zZROCsCkFUk6j07deswI=
  file: dist/aws_lambda_guardduty.zip
  on:
    repo: fortinet/aws-lambda-guardduty
    tags: true
